# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Yarn install
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: Precompile assets
        run: bundle exec rails assets:precompile
      - name: Run tests
        run: bundle exec rake
